### ISSUE TITLE
https://developerlife.com/2022/03/30/rust-proc-macro/ is out of sync with repo and examples are incomplete

### ISSUE THREAD

**Issue by sorhawell** [nazmulidris/rust_scratch#5]
Thank you for writing this tutorial it started out really well for me.
However, at Eg. 1 the supplied code will not run because imports are not mentioned

something like these imports should be in top of `ast_viz_debug.rs`

```
use proc_macro::TokenStream;
use quote::ToTokens;
use r3bl_rs_utils::{style_primary, style_prompt};
use syn::{parse_str, ItemFn};
```

also ast_clone does not implement Display but Debug

```
let ast_clone = ast.clone();
    eprintln!("{} => {}", style_primary("Debug::ast"), ast_clone);
```

I see you have similar examples in your repo, but here the code has changed significantly from the article.

maybe I got into it from a wrong angle I'll just try another tutorial.

**Comment by nazmulidris** [comment]
@sorhawell Thank you for pointing out the build failures. I've fixed in this commit https://github.com/nazmulidris/rust_scratch/commit/c23b9d494251a4b97999d4edab40b87e12743477. Please get the latest version & you will find a new Cargo.lock file.

What happened is that as I've been writing the r3bl_rs_utils repo over the last year, I started using re-exports to make use statements easier. So this broke the import 
`use r3bl_rs_utils::utils::{print_header, style_primary, style_prompt};` since the new version is
`use r3bl_rs_utils::{print_header, style_primary, style_prompt};`

Also, I use `*` in the Cargo.toml for which version of r3bl_rs_utils to use. And in Cargo.lock this was pointing to a really old version of this library. I only use a few functions from this library in the rust_scratch repo anyway.

PLMK if this fixes the issue for you. Also you can find lots of great decl & proc macros in these repos which are under active development. I'm planning to write 2 more articles on these very soon.

1. proc macros: https://github.com/r3bl-org/r3bl_rs_utils/tree/main/macro
2. decl macros: https://github.com/r3bl-org/r3bl_rs_utils/search?q=macro_rules
